### PR TITLE
Added Czech language

### PR DESCRIPTION
**Pull request by petikwastaken**
By the way the comment at the end is my name, feel free to remove it.

### CODE REVIEW

**Comment by Zoey2936** [comment]
Not mandatory, but could you please try to fix DCO?

**Comment by petikwastaken** [comment]
> Not mandatory, but could you please try to fix DCO?

I installed it and how do I sign it?

**Comment by petikwastaken** [comment]
Does it work now? I dont know what the fuck I did, just pasted some commands in to cmd. Hope it works now.

**Comment by Zoey2936** [comment]
yes, thanks, it worked

**Comment by petikwastaken** [comment]
My first pull request to someone's else repo.

**Comment by petikwastaken** [comment]
oh, didnt i fuck it up by closing it?

**Comment by Zoey2936** [comment]
I think the close was accidentally, right?

**Comment by petikwastaken** [comment]
kinda, as I said my first time 💀

**Comment by Zoey2936** [comment]
Just leave it as is, @DavidCraftDev should take a look over it

**Comment by petikwastaken** [comment]
I just  fucked it up again, didnt I?

**Comment by Zoey2936** [comment]
i think not

**Review by DavidCraftDev — APPROVED** [review]
The format of the file is right, it can be merged!

**Pull request merged**
